name: dpo
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgomp=15.1.0=h767d61c_3
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.2=hee844dc_2
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py310ha75aee5_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py310h7c4b9e2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - airportsdata==20250706
      - annotated-types==0.7.0
      - anyio==4.9.0
      - appdirs==1.4.4
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babe==0.0.7
      - beartype==0.14.1
      - bert-score==0.3.13
      - better-abc==0.0.3
      - blake3==1.0.5
      - blessed==1.21.0
      - brotli==1.1.0
      - cachetools==6.1.0
      - cbor2==5.7.0
      - certifi==2025.7.14
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - compressed-tensors==0.11.0
      - config2py==0.1.38
      - contourpy==1.3.2
      - cupy-cuda12x==13.5.1
      - cycler==0.12.1
      - dataclasses==0.6
      - datasets==4.0.0
      - deepspeed==0.17.2
      - depyf==0.19.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dol==0.3.20
      - einops==0.8.1
      - email-validator==2.2.0
      - eval-type-backport==0.2.2
      - fancy-einsum==0.0.3
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.4
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fonttools==4.58.5
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gmpy2==2.2.1
      - gpustat==1.1.1
      - graze==0.1.31
      - h11==0.16.0
      - h2==4.2.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - hyperframe==6.1.0
      - i2==0.1.48
      - idna==3.10
      - importlib-resources==6.5.2
      - interegular==0.3.3
      - jaxtyping==0.3.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lightning-utilities==0.14.3
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - munkres==1.1.4
      - narwhals==2.5.0
      - networkx==3.3
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.65
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.6.0
      - openai-harmony==0.0.4
      - opencv-python-headless==4.12.0.88
      - outlines==0.1.11
      - outlines-core==0.2.11
      - pandas==2.3.1
      - partial-json-parser==0.2.1.1.post6
      - patsy==1.0.1
      - peft==0.16.0
      - pillow==11.0.0
      - plotly==6.3.0
      - plotly-express==0.4.1
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - protobuf==4.25.3
      - py-cpuinfo==9.0.0
      - py2store==0.1.21
      - pyarrow==16.1.0
      - pybase64==1.4.1
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.6
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - ray==2.50.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.5
      - rich==14.0.0
      - rich-toolkit==0.14.8
      - rignore==0.6.2
      - rpds-py==0.26.0
      - sae-lens==6.12.1
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.33.0
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - shtab==1.7.2
      - simple-parsing==0.1.7
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - starlette==0.47.1
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformer-lens==2.16.1
      - transformers==4.57.1
      - transformers-stream-generator==0.0.5
      - triton==3.4.0
      - trl==0.24.0
      - typeguard==4.4.2
      - typer==0.16.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tyro==0.9.17
      - tzdata==2025.2
      - unicodedata2==16.0.0
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.11.0
      - wadler-lindig==0.1.7
      - wandb==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - xformers==0.0.32.post1
      - xgrammar==0.1.25
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.23.0
prefix: /common/users/mg1998/miniforge3/envs/dpo
